version: "1.0"
services:
    php:
      build: ./php-part/
      container_name: t4app-php.docker
      volumes:
        - ./php:/var/www/html
      ports:
        - "9090:80"
    database:
      image: mariadb:latest
      container_name: t4app-db.docker
      ports:
        - "9091:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root1234
        - MYSQL_DATABASE=t4api
        - MYSQL_USER=t4api
        - MYSQL_PASSWORD=t4api1234
        - TZ=Europe/Berlin
      # use this for automatic layout creation
      # volumes:
       # - ./layout.sql/:/docker-entrypoint-initdb.d/init.sql
networks:
  default:
    name: t4application